pipeline {
    agent any
    
    tools {
        maven 'mavenjenkins'
    }
    
    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials')  // Replace with your Jenkins credentials ID
    }
    
    stages {
        stage('Build') {
            steps {
                sh './mvnw spring-boot:build-image "-Dspring-boot.build-image.imageName=hjbarbieri/funkyapp:1.1"'
            }
        }
        // stage('Test') {
        //     steps {
        //         sh 'mvn test'
        //     }
        // }
        stage('Deploy') {
            steps {
                script {
                    // Docker Login
                    sh "echo ${DOCKERHUB_CREDENTIALS_PSW} | docker login -u ${DOCKERHUB_CREDENTIALS_USR} --password-stdin"
                    
                    // Push the Docker image
                    sh 'docker push hjbarbieri/funkyapp:1.1'
                }
            }
        }
    }
}
